name: Task
description: Prepared and described piece of work
title: "Task: <title>"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a brief summary of task
      placeholder: Few lines is enough
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Indicate a list of areas that require extra attention, or give a
        detailed explanation for newcomers
      placeholder: Provide some important to know info
    validations:
      required: false
